cli/args.js
cli/cli.js
cli/package-lock.json
cli/package.json
cli/ws_server.js
web/examples/ws/.gitignore
web/examples/ws/package-lock.json
web/examples/ws/package.json
web/examples/ws/webpack.config.js
web/examples/ws/wsdemo.html
web/examples/ws/wsdemo.js

Allow `halocli` to work as the WebSocket server, so that a webpage could connect and execute arbitrary HaLo commands over PCSC.

Add bridge server functionality

---

docs/api-utils.md
halo/utils.js
index.js
web/weblib.js

Add `haloRecoverPublicKey()` utility function to make it possible to recover public keys out of messages and signatures.

Lib: Add haloRecoverPublicKey() util function

---

.github/workflows/prod_build_cli.yml
cli/args_bridge.js
cli/assets/views/ws_client.html
cli/cli.js
cli/macos_pkgbuild_scripts/postinstall
cli/ws_server.js

Right now halo-bridge is not useable on Mac OS Safari due to strict mixed content policy. Its not possible for HTTPS website to connect with a localhost websocket, even though other browsers and platforms allow that.
The Mac OS installer will just generate a self-signed TLS certificate on users local machine and mark it as trusted.

Bridge: Use selfsigned TLS certificate on Mac OS

---

cli/assets/views/ws_client.html
cli/macos_pkgbuild_scripts/postinstall
cli/ws_server.js

Mac OS installer will give the user an option whether he wants to generate a local certificate or not.

Bridge installer: Ask the user whether he wants to generate a certificate

---

cli/assets/views/ws_client.html
cli/cli.js
cli/ws_server.js
docs/halo-bridge.md

Right now HaLo Bridge could detect YubiKeys or other PC/SC compatible cards. Let's make it so HaLo Bridge will first try to select HaLo Core Applet. The card won't be reported at all if it's not compatible.

Bridge: don't report WebSocket events on cards that are not HaLo compatible

---

web/web_utils.js

Currently, Firefox under Mac OS would first try to connect to `wss://` endpoint, which would always fail anyway. We don't install our self-signed `halo-bridge.local` certificate into Firefox's trust store, so it has no chance to work.
This is not a problem for any other browser, but Firefox would block the second request towards `ws://` until the first request towards `wss://` fails, which could take many seconds. This leads to a timeout on both requests and causes haloFindBridge() being unable to find the correct bridge address.

Bridge: reorder WS/WSS health checks

---

drivers/webnfc.js

Web: Fix bug that was causing WebNFC throwing "retry" error when libhalo is running under frontend frameworks

---

halo/commands.js

Web: Fix WebNFC bug with version C3 when parsing public keys

---

halo/commands.js

Right now it's possible to pass malformed `command.message` or `command.digest` value when signing. The buffer will be incorrectly decoded and this might lead to unexpected results or signing a different value than expected. This PR would introduce input validation for these parameters and fail early if something is malformed.

HaLo: Validate command.message and command.digest for correctness when signing

---

docs/api-web.md
drivers/web.js
web/examples/demo.html
web/soft_prompt.js

Emulate NFC scanning prompt in HTML when `execHaloCmdWeb()` is used with `webnfc` command executor (Android). That would equalize user experience across all platforms when LibHaLo is used in the default configuration.

Web: Add default status callback for Android

---

drivers/credential.js
drivers/web.js
drivers/webnfc.js
web/examples/demo.html
web/soft_prompt.js

Right now the emulated prompt on Android doesn't let the user cancel the NFC operation, although the system-level prompts that appear on Windows/iOS allow the user to cancel the operation without scanning anything.
This PR adds the ability to cancel the operation in the emulated prompt to equalize user experience across all software platforms.

Web: Implement cancel feature for emulated prompt

---

drivers/webnfc.js

Avoid emulated prompt from clipping when the WebNFC permission was previously denied by the user.

Web: Check WebNFC permission before displaying the emulated prompt

---

halo/commands.js

There is a bug in how input is passed to `ethers.utils.hashMessage()` when doing EIP 191 signing of the specified hex message.

Fix bug with EIP191 message signing

---

halo/commands.js

Fix a bug that caused EIP-191 hex-formatted messages to be signed incorrectly (as UTF-8 strings). Add a possibility to pass the message in hex format with `0x` prefix.

HaLo: Fix EIP-191 signing for format=hex.

---

drivers/nfc_manager.js
drivers/pcsc.js
drivers/read_ndef.js

There is a legacy caching functionality in the `readNDEF()` method which causes LibHaLo to cache the first valid NDEF. That is not correct since the lib user might want to scan multiple tags in a single session.

Drivers: Remove caching functionality from readNDEF

---

cli/args_bridge.js
cli/args_cli.js
cli/cli.js

In case when somebody has multiple PC/SC readers attached, we provide a `--reader` CLI option to specify a particular reader that should be used by `halocli` or `halo-bridge`. The list of connected readers can be obtained by using `halocli pcsc_detect` (without any switches).

CLI: Implement --reader switch to specify a particular PC/SC reader.

---

docs/halo-command-set.md
halo/commands.js
halo/keyflags.js

HaLo: Properly parse keySlotFlags and keySlotFailedAuthCtr in get_data_struct

---

cli/assets/static/style.css
cli/assets/views/stats.html
cli/src.ts/args_gateway.ts
cli/src.ts/entry_gateway.ts
cli/src.ts/util.ts

* Gather  "Requestor connected" and "Command request sent to executor" logs and save them to cli/logs/yyyy_dd.ndjson
* Save x-forwarded-for header in logs
* Added stats(/stats) page which displays data about total total connections, total processed commands & total unique IPs for every recorded origin domain for every log present in cli/logs/
* Stats page can be disabled by --disable-stats(-d) flag

Log usage statistics & stats subpage

---

cli/src.ts/simulator_nfc.ts

Simulator: Add missing destroyCardSet() call in simulator_nfc

---

core/src.ts/web/examples/gateway_requestor.html

Added support for selecting whether to send "message" or "digest" in gateway_requestor.html

Gateway requestor: support for sending digest

---

core/src.ts/drivers/web.ts

Historically, the `detectMethod()` function was prioritizing the choice of WebNFC execution method as a default method if it was available on the current platform. This PR will change that in order to always use the `"credential"` execution method, since its general UX has improved a lot in the meantime.

Halo: always pick "credential" execution method by default

---

cli/src.ts/cli.ts

Bridge: Open Burner OS webpage by default when the bridge is started

---

cli/src.ts/ws_server.ts
core/src.ts/halo/exceptions.ts
core/src.ts/halo/gateway/executor.ts

Webpack could sometimes rename the exception's constructor name to e.g. `exceptions_HaloTagError`, which causes that exception not to be recognized properly on the other side of Gateway/Bridge.

Gateway/Bridge: report proper exception class names

---

core/src.ts/drivers/web.ts

Revert detectMethod() implementation back to WebNFC preference where available
