.github/workflows/build_cli.yml
cli/Entitlements.plist
cli/package-lock.json
cli/package.json

Sign halocli build for MacOS

---

.github/workflows/publish_npm.yml

CI: Add publish npm package step

---

.github/pull_request_template.md
cli/args.js
cli/cli.js
drivers/common.js
drivers/pcsc.js
halo/commands.js
halo/tests.js
halo/utils.js
index.js
tests.js
web/tests/tests.html
web/weblib.js

Add semi-automatic test command in HaLo CLI. The command is hidden by default, as it might reconfigure the tag in undesired way and certain configuration might not be possible to rollback.

Add stub for selftest

---

web/tests/tests.html

Fix button padding in web test suite

---

README.md
docs/api-react-native.md
docs/mobile-react-native.md

Fix docs around execHaloCmdRN()

---

cli/actions.js
cli/args.js
cli/cli.js
docs/desktop-cli.md
halo/commands.js

Fix CLI sign command, add output format

---

.github/CODEOWNERS
.github/workflows/build_cli.yml

CI: Pin 3rd party actions to exact commit ID

---

.github/CODEOWNERS
.github/workflows/check_cli.yml
.github/workflows/check_lib.yml
.github/workflows/check_npm.yml
.github/workflows/prod_build_cli.yml
.github/workflows/prod_build_lib.yml
.github/workflows/prod_publish_npm.yml

Refactor CI permissions

---

cli/cli.js

Log message when halocli server is started

---

drivers/pcsc.js

PC/SC: Add environment variable DEBUG_PCSC to debug commands and timings

---

drivers/pcsc.js
halo/errors.js

Return addon version with "halocli version"

---

docs/api-utils.md
halo/commands.js
halo/utils.js
index.js
web/weblib.js

utils: expose haloConvertSignature function

---

cli/assets/views/consent.html
cli/assets/views/consent_error.html
cli/ws_server.js

halo-bridge: add consent page feature

---

cli/package-lock.json
cli/package.json
cli/util.js
cli/ws_server.js

Bridge: Rework how CSRF token works to fix weird bugs

---

.github/workflows/prod_build_cli.yml

The halocli release doesn't just contain halocli alone. Let's rename that to halo-tools so it will make more sense it's plural.

CI: Rename halocli to halo-tools

---

cli/assets/views/ws_client.html
cli/cli.js
cli/macos_pkgbuild_scripts/postinstall
cli/ws_server.js
docs/halo-bridge.md
halo/gateway/executor.js
web/web_utils.js
web/weblib.js

Bridge: Tune the TLS related settings and code

---

index.js

Fix: export haloFindBridge from index.js

---

cli/package-lock.json
cli/package.json
cli/win_fix_binary.js

CI: Fix HaLo tools branding

---

halo/gateway/requestor.js
web/README.md
web/examples/README.md
web/examples/gateway_requestor.html
web/examples/index.html

Gateway: Switch to official gateway server hosted in arx.org

---

web/web_utils.js

All checks seem to hang and timeout when we run wss:// check on Firefox with incorrect certificate. Let's drop this check on Firefox exclusively.

Bridge: Don't run wss:// check on Firefox at all

---

cli/macos_pkgbuild_scripts/postinstall
cli/ws_server.js
docs/halo-bridge.md
web/web_utils.js

Bridge: rename halo-bridge.local to halo-bridge.internal and increase timeout for Firefox

---

web/web_utils.js

Bridge: fix bug in web_utils.js

---

web/examples/demo.html

Web: Fix error in demo

---

docs/api-utils.md
docs/api-web.md
drivers/common.js
drivers/credential.js
drivers/webnfc.js
web/examples/demo.html
web/weblib.js

Web: add haloGetDefaultMethod() and report the current method in statusCallback()

---

index.js

Web: Expose detectMethod() from the dynamic library

---

docs/api-web.md

Add missing documentation for the two new web helper methods.

Add docs for haloGetDefaultMethod() and haloCheckWebNFCPermission()

---

drivers/webnfc.js

Web: Fix how webpage minimization is detected in WebNFC

---

docs/api-web.md
drivers/credential.js
drivers/web.js
drivers/webnfc.js
web/examples/demo.html

Web: Delete debugCallback(), add the "again" status to statusCallback() for completeness

---

drivers/common.js
halo/commands.js

HaLo: implement cmdSetURLSubdomain

---

cli/args_cli.js
docs/halo-command-set.md
drivers/common.js
halo/commands.js
package-lock.json

HaLo Core supports password protection of the key slot 3 since version 01.C5. This PR would add the necessary minimum support for the password locks.

Add support for password set/unset and protected signing

---

api/web.js
halo/gateway/executor.js

Gateway: Essential fixes for React.js integration

---

web/examples/gateway_requestor.html

Gateway: Allow to change the URL in the QR code for debugging

---

README.md
api/desktop.js
docs/desktop-gateway.md
halo/gateway/requestor.js

Gateway: Allow to provide custom WebSocket implementation

---

docs/desktop-gateway.md

Docs: Fix references in desktop-gateway.md

---

docs/desktop-gateway.md
docs/desktop-pcsc.md
docs/mobile-react-native.md

Docs: Fix libhalo npm package references

---

web/soft_prompt.js

Fix CSS styles in emulated prompt.

Web: Fix soft prompt CSS styles

---

docs/api-web.md

Docs: Fix statusCallback documentation

---

web/soft_prompt.js

Web: Adjust CSS for the emulated prompt

---

web/examples/compatible.html
web/examples/demo.html
web/examples/simple.html

Web: Fix comments in demos

---

drivers/web.js
web/soft_prompt.js

Web: Refactor abstractions in defaultStatusCallback()

---

docs/halo-command-set.md

Docs: Add missing information about `format` parameter in sign command.

---

docs/halo-command-set.md
halo/commands.js

Halo: Return etherAddress from sign command and update docs

---

docs/firmware-versions.md

Docs: Clear up the firmware version docs

---

halo/commands.js

Halo: patch sign command for keyNo <= 3

---

cli/assets/static/style.css
cli/assets/views/gateway_executor.html
halo/gateway/executor.js
halo/gateway/requestor.js
web/examples/gateway_requestor.html

Gateway: Propagate error code from executor in case of command fail

---

cli/assets/static/style.css

Gateway: Fix CSS

---

cli/assets/static/style.css
web/examples/gateway_requestor.html
web/soft_prompt.js

Gateway: Update CSS styles and fix bug with emulated prompt

---

cli/args_cli.js
halo/commands.js
halo/flags.js

HaLo: Add new flags to adjust with the C6 version

---

halo/commands.js

Fix cmdGetKeyInfo

---

docs/firmware-versions.md

Update version compatibility

---

.github/workflows/prod_build_cli.yml
.github/workflows/prod_build_lib.yml
.github/workflows/prod_integrity_check.yml

CI: Bump cosign-installer

---

web/examples/index.html

Docs: additional demo links

---

docs/halo-command-set.md
docs/key-slots.md

Docs: adjust HaLo documentation

---

web/examples/gen_key.html

Docs: Fix gen_key demo

---

.github/workflows/prod_build_cli.yml

CI: Fix build for MacOS

---

halo/commands.js

HaLo: Minor fixes in key gen commands

---

halo/commands.js
halo/errors.js

HaLo: Add failed authentication counter in get_key_info

---

halo/commands.js

Fix protocol version in key backup

---

halo/commands.js

HaLo: Fix result processing in key backup

---

web/examples/cfg_ndef.html

Docs: Add cfg_ndef.html demo

---

web/examples/index.html

Docs: Add link to cfg_ndef.html demo

---

web/examples/edge/key_backup.html

Docs: Fix library path in edge/key_backup.html

---

halo/errors.js

HaLo: Add new error code ERROR_CODE_OP_LIMIT_EXCEEDED

---

docs/halo-command-set.md

Docs: add get_data_struct

---

api/common.js
docs/api-utils.md
halo/commands.js
halo/util.js

HaLo: Always reassemble DER signature to avoid formatting errors

---

docs/firmware-versions.md
docs/halo-command-set.md

Docs: Add docs about graffiti commands

---

web/examples/edge/graffiti.html

Examples: Add graffiti web demo.

---

halo/commands.js
halo/keyflags.js

HaLo: Rework key flags reporting

---

halo/commands.js
halo/errors.js

HaLo: Fix graffiti encoding in get_data_struct, update graffiti error code

---

docs/bjj/verify_bjj_rndsig.js
docs/bjj/verify_bjj_rndsig.py

Docs: Add scripts to interact with BJJ RNDSIG

---

halo/commands.js

HaLo: Fix cmdGetTransportPK/cmdLoadTransportPK implementation

---

halo/commands.js

HaLo: Add cfgBytes to the output of cmdCfgNDEF

---

cli/package.json
package.json

Bump version to 1.2.29

---

web/examples/graffiti.html
web/examples/key_backup.html

Docs: Fix bug in demos

---

docs/api-web.md
drivers/credential.js
drivers/web.js
drivers/webnfc.js
halo/util.js

Drivers: Add web debug logs

---

package-lock.json
package.json
web/webpack.config.js

Fix problems with webpack

---

api/web.js
cli/ws_server.js
drivers/pcsc.js
halo/bridge.js
halo/gateway/requestor.js
halo/util.js
web/web_utils.js

implement HaloBridge class and add minor fixes

---

halo/gateway/requestor.js

Gateway: Properly handle NFCOperationError in requestor

---

api/common.js
cli/assets/views/consent_close.html
cli/entry_gateway.js
cli/ws_server.js
halo/bridge.js
halo/exceptions.js
halo/gateway/requestor.js
halo/util.js
web/web_utils.js

Bridge/Gateway: Better exceptions when there is an error related to the transport itself, handle bridge consent properly

---

.github/workflows/prod_build_cli.yml

CI: Fix broken workflow for Windows

---

.github/workflows/prod_build_lib.yml

CI: Minor fix in description

---

.github/workflows/prod_build_cli.yml

CI: Fix asset bundling

---

.github/workflows/check_cli.yml
.github/workflows/check_lib.yml
.github/workflows/prod_build_cli.yml
cli/package.json
cli/webpack.config.js

CI: Reintroduce dry-run checks

---

core/src.ts/drivers/web.ts
core/src.ts/halo/cmd_exec.ts
core/src.ts/halo/command_types.ts
core/src.ts/halo/commands.ts
core/src.ts/halo/gateway/requestor.ts
core/src.ts/types.ts

Halo: Fix OOP API and types

---

core/src.ts/halo/cmd_exec.ts

Halo: Fix error in OOP API invocation

---

.github/workflows/prod_build_lib.yml

CI: Fix package publishing

---

core/package.json
core/src.ts/halo/bridge.ts
core/src.ts/halo/gateway/requestor.ts
core/yarn.lock

Bridge/Gateway: Implement onDisconnect events

---

core/src.ts/halo/commands.ts
core/src.ts/halo/keyflags.ts
core/src.ts/types.ts

Halo: Update key flag meanings

---

core/src.ts/web/examples/gateway_requestor.html

Demos: Allow to override HaLo Gateway URL

---

cli/package.json
cli/yarn.lock
core/src.ts/api/common.ts
core/src.ts/drivers/common.ts
core/src.ts/drivers/pcsc.ts
core/src.ts/halo/simulator.ts
core/src.ts/types.ts

Halo: Implement general simulator API

---

cli/src.ts/entry_gateway.ts
cli/src.ts/util.ts

Gateway: Fix bug with log saving

---

core/src.ts/halo/simulator.ts

Simulator: Wait for welcome packet after connecting.

---

core/src.ts/halo/simulator.ts

Simulator: Add minimal logging features

---

core/src.ts/halo/simulator.ts

Simulator: properly handle HaLo errors

---

core/src.ts/halo/jwe_util.ts

Gateway: Fix problem with shared key serialization

---

core/src.ts/halo/simulator.ts

Simulator: Display console URL upon connecting.

---

core/src.ts/halo/simulator.ts

Simulator: fix URL scheme for simulator

---

core/src.ts/halo/commands.ts

Simulator: Allow to use card duplication commands

---

cli/assets/views/stats.html

Gateway: Remove debug info from stats

---

core/src.ts/halo/simulator.ts

Simulator: Fix console URL construction

---

core/src.ts/halo/simulator.ts

Simulator: Implement swap_card call

---

core/src.ts/halo/simulator.ts

Simulator: Implement resetState() call in HaloSimulator

---

core/src.ts/halo/simulator.ts

Simulator: Expose calls to swapCard() and resetCardSet() through SimHaloAPI

---

cli/package.json
cli/src.ts/args_cli.ts
cli/src.ts/cli.ts
cli/src.ts/entry_cli.ts
cli/src.ts/simulator/nfc.ts
cli/src.ts/util.ts
cli/yarn.lock
core/src.ts/halo/simulator.ts
core/src.ts/types.ts

CLI: Integrate simulator with halocli and halo-bridge

---

cli/src.ts/args_cli.ts
cli/src.ts/entry_cli.ts
core/src.ts/halo/simulator.ts
core/src.ts/types.ts

Simulator: refactor unclear wording around cardId vs csetId

---

cli/src.ts/args_cli.ts
cli/src.ts/simulator/nfc.ts

Simulator: Fix bugs from previous commit

---

cli/src.ts/args_cli.ts
cli/src.ts/cli.ts
cli/src.ts/entry_cli.ts
cli/src.ts/simulator_nfc.ts
core/src.ts/halo/simulator.ts
core/src.ts/types.ts

Simulator: Add missing sim_instance parameter.

---

core/src.ts/halo/simulator.ts

Simulator: Adjust card set destroy/reset API.

---

cli/src.ts/args_cli.ts
cli/src.ts/cli.ts

Simulator: Implement missing sim_destroy command.

---

core/src.ts/web/examples/get_data_struct.html
core/src.ts/web/examples/index.html

* Added an html page with a demo for using get_data_struct command
* Added a link to that demo into index.html
* [] (PR Author) The affected drivers were manually tested

Command demo: get_data_struct

---

core/src.ts/web/examples/get_key_info.html
core/src.ts/web/examples/index.html

Added a demo page showcasing the usage of get_key_info command.

Command demo: get_key_info

---

core/src.ts/web/examples/halo_bridge.html
core/src.ts/web/examples/index.html

* Added a page which guides the user how to use HaLo bridge & runs an example command
* Added a link to HaLo bridge demo page to the index page

Demo: halo-bridge

---

core/src.ts/web/examples/cfg_ndef.html
core/src.ts/web/examples/compatible.html
core/src.ts/web/examples/demo.html
core/src.ts/web/examples/gen_key.html
core/src.ts/web/examples/get_data_struct.html
core/src.ts/web/examples/get_key_info.html
core/src.ts/web/examples/graffiti.html
core/src.ts/web/examples/halo_bridge.html
core/src.ts/web/examples/index.html
core/src.ts/web/examples/key_backup.html
core/src.ts/web/examples/pwd_management.html
core/src.ts/web/examples/simple.html

* Separated example link list into mobile-only, desktop-only and mobile and desktop compatible lists
* Added mobile-only/desktop-only information into individual example pages where applicable
* Standardized demo description styling(set class to "text-muted")

Separate demos into mobile-only, desktop-only and mobile and desktop compatible

---

core/src.ts/web/examples/index.html
core/src.ts/web/examples/typed_data.html

* Added a demo for the usage of typed_data
* Added a link to the demo in index.html

Demo: typed data

---

core/src.ts/halo/commands.ts
core/src.ts/web/examples/get_data_struct.html
docs/halo-command-set.md

Halo: Add compressed public key query in get_data_struct

---

core/src.ts/halo/cmd_exec.ts

Halo: Add new commands to the BaseHaloAPI

---

core/src.ts/drivers/web.ts

Web: Prefer WebNFC execution method for older Chrome browsers

---

core/src.ts/drivers/web.ts

Web: Fix bug with detection

---

core/src.ts/web/examples/key_backup.html

Demos: Allow to specify different source/target key slot number in the halo-backup demo

---

core/src.ts/halo/simulator.ts
core/src.ts/types.ts

Simulator: Fix waiting condition in connect(), allow to call read_ndef command.

---

core/src.ts/halo/simulator.ts

Simulator: Add missing binding for execRawAPDU()

---

core/src.ts/drivers/read_ndef.ts

Add fullURL key in read_ndef command

---

cli/src.ts/ws_server.ts

Bridge: Add burner.pro domains to the default allowlist

---

cli/assets/views/gateway_executor.html
cli/src.ts/util.ts
cli/src.ts/ws_server.ts

Bridge/Gateway: Redact passwords in command logs/prompts

---

cli/package.json
core/package.json

Bump version to 1.10.8

---

core/src.ts/halo/gateway/executor.ts

Gateway: Ensure to use credential execution method for key backup commands

---

core/src.ts/halo/simulator.ts

Simulator: Minor feature adjustments

---

.github/workflows/check_cli.yml
.github/workflows/check_lib.yml
.github/workflows/prod_build_cli.yml
.github/workflows/prod_build_lib.yml
README.md
core/package.json
core/src.ts/viem_account.ts
core/yarn.lock
docs/viem-account.md

Fix Viem account utils & docs

---

cli/src.ts/entry_gateway.ts

Gateway: cache stats for 1 minute after fetching them

---

cli/src.ts/args_bridge.ts
cli/src.ts/ws_server.ts
core/src.ts/halo/bridge.ts

Bridge: Allow to connect without Origin header unless --require-origin is set, fix bug with HaloBridge skipping handle_added event

---

core/src.ts/drivers/nfc_manager.ts

RN: Fix bug in command executor

---

core/src.ts/drivers/common.ts
core/src.ts/drivers/credential.ts
core/src.ts/drivers/nfc_manager.ts
core/src.ts/halo/command_types.ts
core/src.ts/halo/commands.ts

Halo: Allow to provide raw password digest instead of password for signing, fix bug in RN driver

---

.github/workflows/prod_build_cli.yml

CI: Update Windows code signing workflow

---

core/package.json
core/src.ts/api/common.ts
core/src.ts/api/custom.ts
core/src.ts/api/desktop.ts
core/src.ts/api/web.ts
core/src.ts/halo/cmd_exec.ts
core/src.ts/halo/jwe_util.ts
core/yarn.lock

Provide new export api/custom with raw execHaloCmd() and helpers exported, minor refactor

---

cli/src.ts/args_cli.ts
core/src.ts/halo/flags.ts
core/src.ts/web/examples/cfg_ndef.html

Halo: Add new NDEF flag

---

cli/themes/dsc/gateway_executor.html

- Remove the successful scan content changes

Remove success status
